changelog:
  exclude:
    labels:
      - test
      - chore
      - merge conflict
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  categories:
    - title: Dependency updates
      labels:
        - build
    - title: New Features
      labels:
        - feat
    - title: Security updates
      labels:
        - sec
    - title: Bug fixes
      labels:
        - fix
    - title: Documentation updates
      labels:
        - doc
    - title: Other Changes
      labels:
        - "*"
