name: Build and release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

#on:
#  push:
#    tags:
#      - "*"

on: push

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    name: build ${{ matrix.os }}/${{ matrix.arch }}
    strategy:
      matrix:
        include:
          - { runner: macos-latest,  os: darwin,  arch: amd64 }
          - { runner: macos-latest,  os: darwin,  arch: arm64 }
          - { runner: ubuntu-latest, os: linux,   arch: amd64 }
          - { runner: ubuntu-latest, os: linux,   arch: arm64 }
    environment: production
    env:
      CGO: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Set CGO
        if: ${{ matrix.os == 'darwin' }}
        run: echo "CGO=1" >> $GITHUB_ENV

      - name: Extract branch name
        id: branch
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Extract version
        id: version
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Build
        run: |
          mkdir -p "$GITHUB_WORKSPACE/dist/${{ matrix.os }}_${{ matrix.arch }}"
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} CGO_ENABLED=${{ env.CGO }} go build -ldflags "-s -w -X 'main.version=${{ steps.version.outputs.tag }}'" -o "$GITHUB_WORKSPACE"/dist/dl .

      - name: Create artifact
        run: cd "$GITHUB_WORKSPACE"/dist/ && tar -czvf dl-${{ steps.version.outputs.tag }}-${{ matrix.os }}-${{ matrix.arch }}.tar.gz dl

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: binary-${{ matrix.os }}-${{ matrix.arch }}
          path: dist/dl-${{ steps.version.outputs.tag }}-${{ matrix.os }}-${{ matrix.arch }}.tar.gz
          retention-days: 1

