name: Build Go binaries

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set env value
        run: |
          echo binary_path="${GITHUB_WORKSPACE}/bin" >> $GITHUB_ENV
          echo binary_name=$(basename "${GITHUB_REPOSITORY}") >> $GITHUB_ENV
          echo release_tag=$(basename "${GITHUB_REF}") >> $GITHUB_ENV
          echo targets="linux/amd64 linux/arm64 darwin/amd64 darwin/arm64" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.1'
          check-latest: true
          cache: true

      - name: Install gox
        run: |
          go install github.com/mitchellh/gox@latest

      - name: Loading dependencies
        run: go mod download

      - name: Build binary
        run: |
          mkdir -p "${{ env.binary_path }}"
          gox -osarch="${{ env.targets }}" -output="${{ env.binary_path }}/${{ env.binary_name }}_{{.OS}}_{{.Arch}}"

      - name: Compress files
        run: tar cvfz "${{ env.binary_name }}"-"${{ env.release_tag }}".tar.gz config-files bin

      - name: Make release
        run: hub release create -a "${GITHUB_WORKSPACE}"/"${{ env.binary_name }}"-"${{ env.release_tag }}".tar.gz -m "${{ env.release_tag }}" "${GITHUB_REF}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
