name: Build and release

#on:
#  push:
#    tags:
#      - "*"

on: push

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - { runner: macos-latest,  os: darwin,  arch: amd64, tags: netcgo }
          - { runner: macos-latest,  os: darwin,  arch: arm64, tags: netcgo }
          - { runner: ubuntu-latest, os: linux,   arch: amd64, env: CGO_ENABLED=0 }
          - { runner: ubuntu-latest, os: linux,   arch: arm64, env: CGO_ENABLED=0 }
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go version
